### PR TITLE
Mathematics for Computer Science

### PR DESCRIPTION
**Pull request by fabianhjr**
Introduces the reader to most branches of mathematics.

### CODE REVIEW

**Comment by rossant** [comment]
It might be worth calling this section "Mathematics of Computer Science" or something no?

**Comment by fabianhjr** [comment]
This is a general book and covers a lot of topics. (Something along General/Introduction/Misc)

**Comment by rossant** [comment]
Well, it really looks like a book on the mathematics for computer science. :) Could you please rename the section and add the authors? Finally, why put the link to archive.org instead of the link to the PDF itself, like the rest of the list?

**Comment by fabianhjr** [comment]
It is the most recent draft I could find. Will gladly create the Mathematics for Computer Science Section.

**Comment by rossant** [comment]
[This one seems more recent](https://people.csail.mit.edu/meyer/mcs.pdf). Also could you add the authors: Eric Lehman, F Thomson Leighton, Albert R Meyer? Thanks!

**Comment by fabianhjr** [comment]
Done

**Comment by rossant** [comment]
perfect thanks!

**Comment by fabianhjr** [comment]
Be welcomed. C:

**Pull request merged**
