### PR TITLE
Added a link under "general resources" to a Github page with links about "understanding math"

### PR DESCRIPTION
**Pull request by nelson-brochado**
You may want to change the order of the link, if you think it's better.

### CODE REVIEW

**Comment by rossant** [comment]
You put it in the TOC which is automatically-generated, so if it stays here it might be removed the next time the TOC is regenerated! It might be better to put the link in a new subsection (for example, called Notations or something) within `General resources`. It's okay if there's just one link for now in that subsection.

**Comment by nelson-brochado** [comment]
@rossant Are you saying that I should create a subsection under the section "general resources" with an item/link which points to the repository, right?! Anyway, I've not looked at the code you're talking about, clearly, and I will do as I think you want me to do unless you say me otherwise.

**Comment by rossant** [comment]
yep!

**Comment by nelson-brochado** [comment]
@rossant Done. See if that's ok.

**Comment by rossant** [comment]
Yes, that's great, thanks!
Closes #10

**Pull request merged**
